#define OPTION_GOAL_PRIMAGEN_LAIR false
#define OPTION_GOAL_DEFEAT_PRIMAGEN false
#define OPTION_GOAL_LEVELS 0
#define OPTION_GOAL_LEVELS_GIVE_PRIMAGEN_KEYS false
#define OPTION_WEAPON_SANITY true
#define OPTION_OPEN_HUB false
#define OPTION_PROGRESSIVE_WARPS 1
#define OPTION_STARTING_AT_HUB false
#define OPTION_RANDOM_AMMO_MIN 20
#define OPTION_RANDOM_AMMO_MAX 75
#define OPTION_STARTING_INVENTORY_ITEMS
#define OPTION_STARTING_WEAPONS
