#define OPTION_GOAL_PRIMAGEN_LAIR false
#define OPTION_GOAL_DEFEAT_PRIMAGEN false
#define OPTION_GOAL_LEVELS 0
#define OPTION_GOAL_LEVELS_GIVE_PRIMAGEN_KEYS false
#define OPTION_RANDOMIZE_WEAPONS true
#define OPTION_PROGRESSIVE_WARPS 1
#define OPTION_EXCLUDED_LEVELS
#define OPTION_RANDOM_AMMO_MIN 20
#define OPTION_RANDOM_AMMO_MAX 75
#define OPTION_STARTING_INVENTORY_ITEMS
#define OPTION_STARTING_WEAPONS
#define OPTION_LEVEL_KEY_PACKS false
