#define OPTION_GOAL_PRIMAGEN_LAIR false
#define OPTION_GOAL_DEFEAT_PRIMAGEN false
#define OPTION_GOAL_LEVELS 0
#define OPTION_GOAL_LEVELS_GIVE_PRIMAGEN_KEYS false
#define OPTION_RANDOMIZE_WEAPONS true
#define OPTION_PROGRESSIVE_WARPS 1
#define OPTION_EXCLUDED_LEVELS
#define OPTION_RANDOM_AMMO_MIN 20
#define OPTION_RANDOM_AMMO_MAX 75
#define OPTION_STARTING_INVENTORY_ITEMS
#define OPTION_STARTING_WEAPONS
#define OPTION_LEVEL_KEY_PACKS false

#define OPTION_ENEMIZER 0
#define OPTION_ENEMIZER_SPAWNERS false

#define OPTION_BOSS_WEAPON_4 0
#define OPTION_BOSS_WEAPON_5 0
#define OPTION_BOSS_WEAPON_6 0

#define OPTION_WEAPON_BARRIERS true
#define OPTION_WEAPON_BARRIER_1_START 1
#define OPTION_WEAPON_BARRIER_1_MID 2
#define OPTION_WEAPON_BARRIER_1_END 3
#define OPTION_WEAPON_BARRIER_2_START 2
#define OPTION_WEAPON_BARRIER_2_MID 3
#define OPTION_WEAPON_BARRIER_2_END 4
#define OPTION_WEAPON_BARRIER_3_START 2
#define OPTION_WEAPON_BARRIER_3_MID 4
#define OPTION_WEAPON_BARRIER_3_END 4
#define OPTION_WEAPON_BARRIER_4_START 3
#define OPTION_WEAPON_BARRIER_4_MID 5
#define OPTION_WEAPON_BARRIER_4_END 6
#define OPTION_WEAPON_BARRIER_5_START 4
#define OPTION_WEAPON_BARRIER_5_MID 5
#define OPTION_WEAPON_BARRIER_5_END 7
#define OPTION_WEAPON_BARRIER_6_START 4
#define OPTION_WEAPON_BARRIER_6_MID 6
#define OPTION_WEAPON_BARRIER_6_END 8

#define OPTION_PROGRESSIVE_AMMO_COUNT 1
#define OPTION_MAX_BULLET 50
#define OPTION_MAX_SHOTGUN_SHELL 20
#define OPTION_MAX_EXPLOSIVE_SHOTGUN_SHELL 10
#define OPTION_MAX_TEK_ARROW 10
#define OPTION_MAX_TRANQUILIZER_DART 15
#define OPTION_MAX_CHARGE_DART 30
#define OPTION_MAX_PLASMA_ROUND 150
#define OPTION_MAX_SUNFIRE_POD 6
#define OPTION_MAX_BORE 10
#define OPTION_MAX_MINE 10
#define OPTION_MAX_GRENADE 10
#define OPTION_MAX_SCORPION_MISSILE 12
#define OPTION_MAX_FLAME_THROWER 50
#define OPTION_MAX_NUKE_AMMO 5
#define OPTION_MAX_SPEAR 12
#define OPTION_MAX_TORPEDO 3
