import os
import io
import zipfile
import Utils
from worlds.Files import APPlayerContainer
from typing import TYPE_CHECKING
from .locations import LOCATION_TABLE
from .items import ITEM_TABLE
from .options import Goal, PrimagenGoal, PrimagenLair

if TYPE_CHECKING:
    from . import Turok2World
    
class Turok2Container(APPlayerContainer):
    game: str = 'Turok 2'

    def __init__(self, rando_replacements: str, ap_settings: str, 
                base_path: str, output_directory: str,
                 player=None, player_name: str = "", server: str = ""):
        self.rando_replacements = rando_replacements
        self.ap_settings = ap_settings
        self.file_path = base_path
        container_path = os.path.join(output_directory, base_path)
        self.patch_file_ending = ".apturok2"
        super().__init__(container_path, player, player_name, server)

    def write_contents(self, opened_zipfile: zipfile.ZipFile) -> None:
        """
        Writes the contents of the patch_data into rando.kpf, so the player
        can drop it off in their Turok 2 mod folder.
        """
        kpf_buffer = io.BytesIO()
        with zipfile.ZipFile(kpf_buffer, "w", zipfile.ZIP_DEFLATED) as kpf_zip:
            kpf_zip.writestr("rando/randoReplacements.as", self.rando_replacements)
            kpf_zip.writestr("rando/apSettings.as", self.ap_settings)
            
        opened_zipfile.writestr("rando.kpf", kpf_buffer.getvalue())
        super().write_contents(opened_zipfile)
        
def gen_turok2_seed(self: "Turok2World", output_directory: str):
    seed_name = self.multiworld.seed_name
    ap_version = Utils.__version__
    player_name = self.multiworld.get_file_safe_player_name(self.player)
    
    header =  f"""
/*
 * This code was generated by Archipelago version {ap_version} for player {player_name}.
 * Place the containing .kpf in your Turok 2 mods folder, alongside the other ones for the rando.
 */
 
"""
    mod_name = f"AP-{seed_name}-P{self.player}-{self.multiworld.get_file_safe_player_name(self.player)}"
    mod_dir = os.path.join(output_directory, mod_name + "_" + ap_version + ".zip")
    mod = Turok2Container(
        get_angelscript_from_filled_locations(self),
        get_settings_string(self),
        mod_dir, 
        output_directory, 
        self.player,
        header + self.multiworld.get_file_safe_player_name(self.player))
    mod.write()
    
def get_angelscript_from_filled_locations(self: "Turok2World") -> str:
    """
    Gets the AngelScript code needed for the mod to place the correct
    actors for the randomized locations.
    """
    angelscript_snippets = []
    for location in self.multiworld.get_filled_locations(self.player):
        # This is an event, so we don't care about it
        if location.address is None:
            continue
        
        location_name = location.name
        location_id = LOCATION_TABLE[location_name]["ap_id"]
        location_position = LOCATION_TABLE[location_name]["position"]
        
        snippet = f"AddReplacement(\"{location_name}\", {location_id}, \"{location_position}\""
        
        # If the item is for this world, the actor id should be the last parameter
        if location.item and location.item.player == self.player:
            snippet += f", {ITEM_TABLE[location.item.name]["actor_id"]});"
        # Else, it should be the location name and player name (so we can display it on pickup)
        else:
            if location.item.advancement:
                is_progression = "true"
            else:
                is_progression = "false"
            player_name = self.multiworld.get_player_name(location.item.player)
            snippet += f", \"{player_name}'s {location.item.name}\", {is_progression});"
        
        angelscript_snippets.append(snippet)
        
    return "\n".join(angelscript_snippets)    
    
def get_settings_string(self: "Turok2World") -> str:
    """
    Gets the macro file with any settings the game needs to know.
    
    Goal:
    - OPTION_GOAL_PRIMAGEN_LAIR: Whether entering the lair is the goal
    - OPTION_GOAL_DEFEAT_PRIMAGEN: Whether defeating the Primagen is the goal
    - OPTION_GOAL_TOTEMS: How many totems is the goal (0 to disable)
    - OPTION_GOAL_TOTEMS_GIVE_PRIMAGEN_KEYS: Whether reaching the totem goal should give all primagen keys
    - OPTION_INCLUDE_WEAPONS_AND_AMMO: Whether weapons and ammo are shuffled (used for replacing ammo spawns)
    
    Inclue weapon and ammo locations:
    - Used to determine whether to replace some generators with the random ammo pack
      to prevent ammo starvation in some maps where you get temporarily trapped inside
    """
    # Defaults - will result in no goal
    primagen_lair_is_goal = "false"
    defeat_primagen_is_goal = "false"
    totems_goal = 0
    totems_give_primagen_keys = "false"
    weapon_and_ammo_setting = "false"

    # Totem goal - just set the goal
    if self.options.goal == Goal.option_totems:
        totems_goal = self.options.totems_goal

    # Primagen goal
    elif self.options.goal == Goal.option_primagen:
        # Set whether totems give primagen keys
        if self.options.primagen_lair == PrimagenLair.option_totems:
            totems_goal = self.options.totems_goal
            totems_give_primagen_keys = "true"
    
        # Set whether the goal is to get to the lair or to defeat the Primagen
        if self.options.primagen_goal == PrimagenGoal.option_get_to_lair:
            primagen_lair_is_goal = "true"
        elif self.options.primagen_goal == PrimagenGoal.option_defeat:
            defeat_primagen_is_goal = "true"

    # Weapon and ammo locations
    if self.options.include_weapon_and_ammo_locations:
        weapon_and_ammo_setting = "true"

    return (f"#define OPTION_GOAL_PRIMAGEN_LAIR {primagen_lair_is_goal}\n" +
        f"#define OPTION_GOAL_DEFEAT_PRIMAGEN {defeat_primagen_is_goal}\n" +
        f"#define OPTION_GOAL_TOTEMS {totems_goal}\n" +
        f"#define OPTION_GOAL_TOTEMS_GIVE_PRIMAGEN_KEYS {totems_give_primagen_keys}\n" +
        f"#define OPTION_INCLUDE_WEAPONS_AND_AMMO {weapon_and_ammo_setting}\n")