import os
import io
import zipfile
import Utils
from worlds.Files import APPlayerContainer
from typing import TYPE_CHECKING
from .locations import LOCATION_TABLE
from .items import ITEM_TABLE

if TYPE_CHECKING:
    from . import Turok2World
    
class Turok2Container(APPlayerContainer):
    game: str = 'Turok 2'

    def __init__(self, patch_data: str, base_path: str, output_directory: str,
                 player=None, player_name: str = "", server: str = ""):
        self.patch_data = patch_data
        self.file_path = base_path
        container_path = os.path.join(output_directory, base_path)
        self.patch_file_ending = ".kpf"
        super().__init__(container_path, player, player_name, server)

    def write_contents(self, opened_zipfile: zipfile.ZipFile) -> None:
        """
        Writes the contents of the patch_data into rando.kpf, so the player
        can drop it off in their Turok 2 mod folder.
        """
        kpf_buffer = io.BytesIO()
        with zipfile.ZipFile(kpf_buffer, "w", zipfile.ZIP_DEFLATED) as kpf_zip:
            kpf_zip.writestr("rando/randoReplacements.txt", self.patch_data)
            
        opened_zipfile.writestr("rando.kpf", kpf_buffer.getvalue())
        super().write_contents(opened_zipfile)
        
def gen_turok2_seed(self: "Turok2World", output_directory: str):
    seed_name = self.multiworld.seed_name
    ap_version = Utils.__version__
    player_name = self.multiworld.get_file_safe_player_name(self.player)
    
    header =  f"""
/*
 * This code was generated by Archipelago version {ap_version} for player {player_name}.
 * Place the containing .kpf in your Turok 2 mods folder, alongside the other ones for the rando.
 */
 
"""
    mod_name = f"AP-{seed_name}-P{self.player}-{self.multiworld.get_file_safe_player_name(self.player)}"
    mod_dir = os.path.join(output_directory, mod_name + "_" + ap_version + ".zip")
    mod = Turok2Container(
        get_angelscript_from_filled_locations(self),
        mod_dir, 
        output_directory, 
        self.player,
        self.multiworld.get_file_safe_player_name(self.player))
    mod.write()
    
def get_angelscript_from_filled_locations(self: "Turok2World") -> str:
    """
    Gets the AngelScript code needed for the mod to place the correct
    actors for the randomized locations.
    """
    angelscript_snippets = []
    for location in self.multiworld.get_filled_locations(self.player):
        location_name = location.name
        location_id = LOCATION_TABLE[location_name]["ap_id"]
        location_position = LOCATION_TABLE[location.name]["position"]
        actor_id = ITEM_TABLE[location.item.name]["actor_id"]
        
        angelscript_snippets.append(f"AddReplacement(\"{location_name}\", {location_id}, \"{location_position}\", {actor_id});")
        
    return "\n".join(angelscript_snippets)