// This will be generated by a separate script for logic calculations
// Format: AddReplacement("<LOC NAME>", <AP_ID>, "<MAP POSITION>", <ACTOR ID>);
//
// AddReplacement("PoA Start - LF1 on Box", 51000, "51_702_-660_-153", kActor_Item_AmmoQuiver);



